#spring:
#  application:
#    name: deadliner-service
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/deadliner
#    platform: POSTGRESQL
#    username: pagrom
#    password: Grom1997
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      dialect: org.hibernate.dialect.PostgreSQL9Dialect
##      show_sql: true
#    properties.hibernate.temp.use_jdbc_metadata_defaults: false
#
#
#server:
#  port: 8080